version: 2

models:
  - name: dim_orders
    description: first dim of the tuto énorme
    columns:
      - name: order_id
        description: tjrs la meme, la primary key
        tests:
          # Generic test that we define in tests/generic/test_primary_key.sql
          # Takes arguments for model & column_name, both of which are automatically passed to it
          - primary_key:
              severity: error
          - unique:
              severity: error
          - relationships:
              to: ref('stg_ecommerce__orders')
              field: order_id
              severity: error
            

      - name: order_created_at
        description: blabla

      - name: order_shipped_at
        description: bloubli

      - name: order_delivered_at
        description: bleble

      - name: order_returned_at
        description: bleubleu

      - name: order_status
        description: "{{ doc('status') }}"

      - name: num_items_ordered
        description: ""

      - name: total_sale_price
        description: "Sum of item_sale_price for the whole order"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0

      - name: total_product_cost
        description: "Sum of product_cost for the whole order"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0

      - name: total_profit
        description: "Sum of (item_sale_price - product_cost) for the whole order"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0

      - name: total_discount
        description: "Sum of (product_retail_price - item_sale_price) for the whole order"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
