version: 2

models:
  - name: int_ecommerce__order_items_products
    description: Join between order item and product
    columns:
      - name: order_item_id
        description: The id of the order item
        tests:
          - not_null:
              severity: error
          - unique:
              severity: error

      - name: order_id
        description: the id of the order
        tests:
          - not_null
      
      - &user_id_definition
        name: user_id
        description: Le petit user id tu connais
        tests:
          - not_null

      - name: product_id
        description: ""

      - name: item_sale_price
        description: ""

      - name: product_department
        description: ""

      - name: product_cost
        description: Combien ca coute dis donc

      - name: product_retail_price
        description: ""

      - name: item_profit
        description: ""

      - name: item_discount
        description: oui

  - name: int_ecommerce__first_order_created
    description: r
    columns:
      - *user_id_definition

# If you didn't want to bring everything through from the anchor you could do this:
# - <<: *user_id
#   description: "New description"
# This would keep the name & tests defined in the anchor, but overwrite the description